### PR TITLE
node-pre-gyp support

### PR DESCRIPTION
**Pull request by imlucas**
- binaries will be built on demand for linux and windows
- just bump the version number in package.json (e.g. `npm version
patch`), commit+push, and appveyor and travis will test and deploy new
prebuilt binaries as needed
- binaries are “maybe built” via a posttest hook for minimal
duplication in CI configs
- binaries live on S3 behind https://bin.mongodb.org/ (all in the
devops production environment, fully managed and maintained by them)
which is fronted by CloudFront (CDN)
- using mongodb-js fork of node-pre-gyp for easier tooling integration

Good to go when this appveyor build finishes for iojs: https://ci.appveyor.com/project/imlucas/bson-ext/build/1.0.34

[Review on Reviewable](https://reviewable.io/reviews/christkv/bson-ext/1)

### CODE REVIEW

**Comment by imlucas** [comment]
fixes mongodb/js-bson#120 mongodb/js-bson#118 mongodb/js-bson#114 mongodb/js-bson#111 iojs/io.js#1245

**Comment by nathanpeck** [comment]
This change has broken the `bson` for me across both Ubuntu and Mac. It was working perfect before in version 0.1.0, but now `bson` is pulling in the new version 0.1.1 since it is requesting version `~0.1` and the BSON module is now failing with errors across both local Mac envs, and Ubuntu machines I'm working with.

**Comment by christkv** [comment]
what error are you seeing as I cannot repro

**Comment by nathanpeck** [comment]
Here is the root issue: https://github.com/christkv/bson-ext/issues/2

**Comment by skotchio** [comment]
It's seems I have this problem related to https://github.com/Automattic/mongoose/issues/2905

**Comment by skotchio** [comment]
@nathanpeck did you resolve the issue?

**Comment by nathanpeck** [comment]
Yes, they fixed the issue by releasing a new version of the package that didn't have a precompiled Mac OS X binary inside of it. You should be able to `npm cache clean; npm rm -rf mongoose; npm install` to fix it.

**Comment by skotchio** [comment]
@nathanpeck thanks for the answer

**Pull request merged**
