### PR TITLE
Updated to new buffer api.

### PR DESCRIPTION
**Pull request by mrseth**

### CODE REVIEW

**Comment by mrseth** [comment]
I ran npm test and it passed all tests.

**Comment by christkv** [comment]
can you check if it passes on 0.10 and 0.8. If it does I'll merge the change.

**Comment by mrseth** [comment]
Yes, it passes.

**Comment by christkv** [comment]
alright I plan to look at the whole BSON stack soon as I want to try again to see if I can get pure js perf close enough to C++ that I can ditch this whole nightmare of an extension. At least then I would only be stuck maintaining the Kerberos extension which a tiny tiny set of users are interested in. Otherwise I might just bite the bullet and make this a

```
npm install -g bson-ext
```

And have you manually install it globally to avoid the 100s of issues with io.js version, node version, os etc.

**Comment by mrseth** [comment]
Eh? I thought you committed a change that made this merge obsolete a while ago.

**Comment by christkv** [comment]
you are confusing the BSON module with this c++ module :) but yes this one is retired but for some reason people keep sending me pull requests and I'm happy to merge them

**Comment by mrseth** [comment]
So the whole driver got a more slim design with less moving parts?

**Pull request merged**
