### PR TITLE
upgrade to nan 2.0.9

### PR DESCRIPTION
**Pull request by guymguym**

### CODE REVIEW

**Comment by guymguym** [comment]
oops, fails on 0.10

**Comment by guymguym** [comment]
@christkv @globlee
I see that windows build are broken from before so that's unrelated.
anyway this is for issue #26.

notes:

* I used some macros and two overloaded functions to hide a bit of the complexity of MaybeLocal. This is due to personal taste and if you think this is unneeded on top of Nan then I can simply unfold these macros instead.

* I converted 2 of the calls to `NanNewBufferHandle(ptr, len)` to `Nan::CopyBuffer(ptr, len)` because as I understood that memory should not be in the responsibility of the new buffer to free. When I tried to use `Nan::NewBuffer()` in these cases I immediately got double free memory so that's clearly not suitable. But I am not sure I follow the memory handling enough so would appreciate a review.

Cheers!

**Comment by guymguym** [comment]
travis/appveyor still dont have a config to run iojs v3 and nodejs v4, so now can be added

**Comment by guymguym** [comment]
hey @christkv, would love to get feedback, make fixes, and get it merged. thanks!

**Comment by christkv** [comment]
I will have a look on Friday, currently giving a training away from home so no time until then

**Comment by guymguym** [comment]
:+1: great thanks!

**Comment by VikramTiwari** [comment]
@guymguym I tried changing the config for appveyor to run with latest node version, as the functions in the file are supposed to run on newer V8.

Though the build did not succeed, you can find error at https://ci.appveyor.com/project/VikramTiwari/bson-ext

**Comment by VikramTiwari** [comment]
@christkv I did test on my end as well (node v4.1.0 and npm v2.14.3) and here's the result

```
$ npm test

> bson-ext@0.1.12 test /Users/Vikram/Documents/code/vikram/bson-ext
> nodeunit ./test/node


bson_test
✔ Should Correctly create ObjectID and do deep equals
✔ Should Correctly convert ObjectID to itself
✔ Should Correctly Deserialize object
✔ Should Correctly Deserialize object with all types
✔ Should Serialize and Deserialize String
✔ Should Serialize and Deserialize Empty String
✔ Should Correctly Serialize and Deserialize Integer
✔ Should Correctly Serialize and Deserialize null value
✔ Should Correctly Serialize and Deserialize Number 1
✔ Should Correctly Serialize and Deserialize Object
✔ Should correctly ignore undefined values
{ doc: {}, a: [ 1, 2, null, 3 ] }
✔ Should correctly serialize undefined array entries as null values
✔ Should Correctly Serialize and Deserialize Array
✔ Should Correctly Serialize and Deserialize Buffer
✔ Should Correctly Serialize and Deserialize Number 4
✔ Should Correctly Serialize and Deserialize Array with added on functions
✔ Should correctly deserialize a nested object
✔ Should Correctly Serialize and Deserialize A Boolean
✔ Should Correctly Serialize and Deserialize a Date
✔ Should Correctly Serialize and Deserialize a Date from another VM
✔ Should Correctly Serialize nested doc
✔ Should Correctly Serialize and Deserialize Oid
✔ Should Correctly encode Empty Hash
✔ Should Correctly Serialize and Deserialize Ordered Hash
✔ Should Correctly Serialize and Deserialize Regular Expression
✔ Should Correctly Serialize and Deserialize a Binary object
✔ Should Correctly Serialize and Deserialize a Type 2 Binary object
(node) Buffer.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
✔ Should Correctly Serialize and Deserialize a big Binary object
✔ Should Correctly Serialize and Deserialize DBRef
✔ Should Correctly Serialize and Deserialize partial DBRef
✔ Should Correctly Serialize and Deserialize simple Int
✔ Should Correctly Serialize and Deserialize Long Integer
✔ Should Deserialize Large Integers as Number not Long
✔ Should Correctly Serialize and Deserialize Long Integer and Timestamp as different types
✔ Should Always put the id as the first item in a hash
✔ Should Correctly Serialize and Deserialize a User defined Binary object
✔ Should Correclty Serialize and Deserialize a Code object
✔ Should Correctly serialize and deserialize and embedded array
✔ Should Correctly Serialize and Deserialize UTF8
✔ Should Correctly Serialize and Deserialize query object
✔ Should Correctly Serialize and Deserialize empty query object
✔ Should Correctly Serialize and Deserialize array based doc
✔ Should Correctly Serialize and Deserialize Symbol
✔ Should handle Deeply nested document
✔ Should handle complicated all typed object
✔ Should Correctly Serialize Complex Nested Object
✔ Should correctly massive doc
✔ Should Correctly Serialize/Deserialize regexp object
✔ Should Correctly Serialize/Deserialize complicated object
✔ Should Correctly Serialize/Deserialize nested object
✔ Should Correctly Serialize/Deserialize nested object with even more nesting
✔ Should Correctly Serialize empty name object
✔ Should Correctly handle Forced Doubles to ensure we allocate enough space for cap collections
✔ Should deserialize correctly
✔ Should correctly serialize and deserialize MinKey and MaxKey values
✔ Should correctly serialize Double value
✔ ObjectID should correctly create objects
✔ ObjectID should correctly retrieve timestamp
✔ Should Correctly throw error on bsonparser errors
✔ Should correctly calculate the size of a given javascript object
✔ Should correctly calculate the size of a given javascript object using instance method
✔ Should correctly serializeWithBufferAndIndex a given javascript object
✔ Should correctly serializeWithBufferAndIndex a given javascript object using a BSON instance
✔ Should correctly serialize a given javascript object
✔ Should correctly serialize a given javascript object using a bson instance
✔ Should correctly deserialize a buffer using the BSON class level parser
✔ Should correctly deserializeStream a buffer object
✔ ObjectID should have a correct cached representation of the hexString
✔ Should fail to create ObjectID due to illegal hex code

test_full_bson
✔ Should Correctly Deserialize object with all types
✔ Should Serialize and Deserialize String
✔ Should Correctly Serialize and Deserialize Integer
✔ Should Correctly Serialize and Deserialize null value
✔ Should Correctly Serialize and Deserialize undefined value
✔ Should Correctly Serialize and Deserialize Number 3
✔ Should Correctly Serialize and Deserialize Object
✔ Should Correctly Serialize and Deserialize Array
✔ Should Correctly Serialize and Deserialize Array with added on functions
✔ Should Correctly Serialize and Deserialize A Boolean
✔ Should Correctly Serialize and Deserialize a Date
✔ Should Correctly Serialize and Deserialize Oid
✔ Should Correctly Serialize and Deserialize Buffer
✔ Should Correctly encode Empty Hash
✔ Should Correctly Serialize and Deserialize Ordered Hash
✔ Should Correctly Serialize and Deserialize Regular Expression
✔ Should Correctly Serialize and Deserialize a Binary object
✔ Should Correctly Serialize and Deserialize a big Binary object
✔ Should Correctly fail due to attempting serialization of illegal key values

to_bson_test
✔ Should correctly handle toBson function for an object
✔ Should correctly handle embedded toBson function for an object
✔ Should fail when top level object returns a non object type

OK: 55887 assertions (790ms)
```

**Comment by guymguym** [comment]
@VikramTiwari I see in travis that the error is:
```
In file included from ../ext/bson.cc:14:0:
/home/travis/.node-gyp/4.1.1/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.1/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.1/include/node/v8.h:852:1: error: expected unqualified-id before ‘using'
```

which is caused by this v8.h code:

```
#if !defined(V8_IMMINENT_DEPRECATION_WARNINGS)
// Local is an alias for Local for historical reasons.
template <class T>
using Handle = Local<T>;
#endif
```

so perhaps the compiler used on the travis build is too old to understand this template using syntax?

**Comment by guymguym** [comment]
@VikramTiwari on appveyor I think it fails on the `Should Correctly Serialize and Deserialize Regular Expression` test. but I't not sure why Nan::New<RegExp> would would behave differently on windows vs linux/mac and return a MaybeLocal that is empty... any ideas?

**Comment by likethesky** [comment]
Total node newb here: is there a way to use this fork now (since I'm running on OS X and Linux servers only)? I'd need instructions on how to do so, if there is a way.

**Comment by guymguym** [comment]
OK I found that the reason for the failure was that persistent handles were leaking, so all the allocated buffers were not released. 

This was the reason for the failure on windows (malloc returned NULL and then NewBuffer return empty handle which resulted the fatal error). 

So the leak is fixed now.

btw it seems that appveyor test also succeeded and only failed trying to publish to s3...

I used valgrind on the nodeunit tests, and while the major leak is gone, I still see indirect lost buffers, which I think are simply caused by BSON objects not being freed by the garbage collector, and I would be happy to validate this but was not sure how.

**Comment by guymguym** [comment]
@likethesky this fork is not yet available on npm, so in the meanwhile you can try 
```
git clone https://github.com/guymguym/bson-ext.git ./node_modules/bson-ext
cd ./node_modules/bson-ext
npm install
npm test
cd -
```

**Comment by guymguym** [comment]
I added a simple leak test that runs 2000 serialize & deserialize and checks that the process memory did not increase more than expected.

**Comment by guymguym** [comment]
hey @christkv, got time to review? thanks!

**Pull request merged**
